name: Docker Caching
description: Cache a docker image

inputs:
  dockerdir:
    required: true
    type: string
  imagename:
    required: true
    type: string
  target:
    required: false
    type: string
  dockerfile:
    required: true
    type: string

runs:
  using: composite

  steps:
    - name: Check for cached docker image
      id: cached-docker
      uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      with:
        path: dockerimage-${{ hashFiles(inputs.dockerfile) }}.tar
        key: ${{ runner.os }}-dockerimagetar-${{ hashFiles(inputs.dockerfile) }}
        restore-keys: ${{ runner.os }}-dockerimagetar-

    - name: Load docker image
      run: docker load --input dockerimage-*.tar || true
      shell: bash

    - name: Build/label docker image
      run: docker build -t ${{ inputs.imagename }} -f ${{ inputs.dockerfile }} ${{ inputs.dockerdir }} --target=${{ inputs.target }} --cache-from ${{ inputs.imagename }}:latest
      shell: bash

    - name: Save docker image
      if: steps.cached-docker.outputs.cache-hit != 'true'
      run: docker save --output dockerimage-${{ hashFiles(inputs.dockerfile) }}.tar ${{ inputs.imagename }}:latest $(docker history -q ${{ inputs.imagename }}:latest | grep -v missing)
      shell: bash

    - name: Always save cache
      uses: actions/cache/save@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4.0.0
      if: steps.cached-docker.outputs.cache-hit != 'true'
      with:
        path: dockerimage-${{ hashFiles(inputs.dockerfile) }}.tar
        key: ${{ runner.os }}-dockerimagetar-${{ hashFiles(inputs.dockerfile) }}
