name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read

    steps:
      - name: Checkout main project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          submodules: true

      - name: Docker cache
        uses: ./.github/workflows/dockercache
        with:
          dockerdir: .
          imagename: svr2_buildenv
          target: builder
          dockerfile: docker/Dockerfile

      - name: Test
        run: make docker_enclave_test

      - name: Build
        run: make

      - name: Validate
        run: make docker_validate

      - name: Valgrind
        run: make docker_enclave_valgrind
